# Port Metadata
PORTNAME =          libADX
PORTVERSION =       1.0.0

MAINTAINER =        SiZiOUS <sizious@gmail.com>
LICENSE =           BSD 2-Clause License
SHORT_DESC =        Library for decoding ADX audio files

KOS_MAKEFILE =      Makefile

# What files we need to download, and where from.
GIT_REPOSITORY =    https://github.com/sega-dreamcast/libadx.git
TARGET =            libADX.a
INSTALLED_HDRS =    include/adx.h include/snddrv.h
HDR_INSTDIR =       adx

include ${KOS_PORTS}/scripts/kos-ports.mk
